### ISSUE TITLE
Required for Checkbox?

### ISSUE THREAD

**Issue by 0711levski** [mbrookes/formsy-material-ui#101]
Hey there,

first of all, thank you for the good work! Is it possible to require at least one checked checkbox?

I tried this, but the form doesn't invalidate:
`<FormsyCheckbox
											label="Bla"
											id="bla"
											name="bla"
											defaultChecked={this.state.bla}
											onChange={this.handleCheckboxChange}
											required
										/>`
										`<FormsyCheckbox
											label="BlaBla"
											id="blabla"
											name="blabla"
											defaultChecked={this.state.blabla}
											onChange={this.handleCheckboxChange}
											required
										/>`

Thanks!

**Comment by MuffinLightning** [comment]
I would also like an answer to this.

**Comment by mbrookes** [comment]
Hi, unfortunately, this is a formsy-react issue.
