### ISSUE TITLE
Update 0.2.3 tag on npm

### ISSUE THREAD

**Issue by vijayrawatsan** [mbrookes/formsy-material-ui#11]
@mbrookes Please update latest tag  0.2.3 on npm. 

Thanks

**Comment by mbrookes** [comment]
Version bumped in packages.json, README updated, published to npm. I didn't force reset the tag with these changes.

**Comment by vijayrawatsan** [comment]
@mbrookes I did a mistake in v0.2.3. I have fixed that mistake and applied this approach
https://github.com/christianalfoni/formsy-react/wiki/validate-on-blur
in following pr. Please have a look and let me know if I can merge. 
https://github.com/mbrookes/formsy-material-ui/pull/12

Thanks

**Comment by mbrookes** [comment]
@vijayrawatsan Can you briefly explain what broke, and how this fixes it? Thanks.

**Comment by vijayrawatsan** [comment]
What broke?
Basically my previous commit added value={this.getValue() to FormsyText which was earlier ommited and looked the right thing to do(https://github.com/christianalfoni/formsy-react/pull/117). 
Issue was there due to onBlur,
formsy-material-ui FormsyText uses onBlur instead of onChange. Due to this after the first onBlur on any inputtext I was not able to change the value of that text field as next value change will happen on onBlur but value is referring to this.getValue()

I tried to be as clear as possible do let me know if you did not understand.

In my new pull request I used this approach to validate FormsyText
https://github.com/christianalfoni/formsy-react/wiki/validate-on-blur 
which is the best possible way till now to validate and looks natural.

**Comment by mbrookes** [comment]
Closing this since npm is updated (albeit with a broken version). FWIW it originally had `value={this.getValue(0}` when validation was onChange, but it subsequently appeared redundant. Clearly that wasn't the case! :)

We can move the discussion to the relevant PR.
