### ISSUE TITLE
Needs a new release / NPM and Repo out of sync

### ISSUE THREAD

**Issue by ornj** [mbrookes/formsy-material-ui#112]
Current version is 0.4.3 but the package downloaded from NPM doesn't match what is currently in master.

I noticed that `FormsyText` was not updating it's value when given new props and found that `componentWillReceiveProps` is missing in the released package.

**Comment by mbrookes** [comment]
> NPM and Repo out of sync

That's how development happens. If we didn't update the repo, we wouldn't have anything to release.

**Comment by ornj** [comment]
Indeed. Do you have plans on another release or just "it happens when it happens"?

**Comment by mbrookes** [comment]
Normally as soon as an issue is resolved - in this instance once #109 and #111 are merged. What's on master isn't quite there.
