### ISSUE TITLE
Integrating with a typescript project

### ISSUE THREAD

**Issue by Vaevictus** [mbrookes/formsy-material-ui#117]
Hi there,

I got caught out by material-ui; I thought it had form field validation built in. Anyway, I saw that this project is the recommended way of bringing in forms validation into a material-ui based project.

I've used Typescript (TSX) using the typings from definitelytyped to build my project, and I want to know how I can make use of your library within my project. Definitelytyped repo has neither type defs for this project nor the dependency formsy-react. Is there any way I can use your library without them? I'm going in circles on google.......

Cheers

**Comment by asafshen** [comment]
just put the following text under `some-file-name.d.ts` in your project's `typings` directory:

```
declare module "formsy-react" {
  const Formsy:any;
  export = Formsy;
}

declare module "formsy-material-ui/lib" {
  import * as React from "react";

  export class FormsyCheckbox extends React.Component<any, any> {}
  export class FormsyDate extends React.Component<any, any> {}
  export class FormsyRadio extends React.Component<any, any> {}
  export class FormsyRadioGroup extends React.Component<any, any> {}
  export class FormsySelect extends React.Component<any, any> {}
  export class FormsyText extends React.Component<any, any> {}
  export class FormsyTime extends React.Component<any, any> {}
  export class FormsyToggle extends React.Component<any, any> {}
}

```

**Comment by mbrookes** [comment]
Thanks @asafshen.
