### ISSUE TITLE
React 15.2 issues warnings for unknown props.

### ISSUE THREAD

**Issue by jayalfredprufrock** [mbrookes/formsy-material-ui#119]
I'm preparing a pull request to fix this, but seeing as I'm not using all the different input types in my app that formsy-material-ui supports, it could probably use some additional testers.

**Comment by DrkCoater** [comment]
I'm also seeing unknown "validations", "validation-errors" props.

**Comment by rigelk** [comment]
Also having those warnings with FormsySelect (`menuItems`, `validationError`, `validationErrors`) and FormsyText (`validations`).

**Comment by DrkCoater** [comment]
Can someone fix it pls? It's blocking my ReactJS upgrade. I can help testing.

**Comment by DrkCoater** [comment]
thanks!
