### ISSUE TITLE
Validate only when field touched

### ISSUE THREAD

**Issue by tb** [mbrookes/formsy-material-ui#121]
I have list of editable objects. When I add someobject to the list, it initially has name = "" and I can see "required" validation fails.

How can I prevent validation if field was not "touched" by user?

My input code looks like this:

    <FormsyText
      name="name"
      defaultValue={someobject.name}
      validations={this.nameValidations(someobject, someobjects)}
      validationErrors={this.nameValidationErrors()}
      onBlur={(e) => this.updateSomeObject({...someobject, name: e.target.value})}
    />

This is how I was able to do it in redux-form:

    <TextField
      errorText={someobject.name.touched && someobject.name.error}
      {...someobject.name}
    />

**Comment by MuffinLightning** [comment]
I would also like an answer to this.

**Comment by tb** [comment]
By implementing my own FormsyText I was able to set state.touched on blur and use it like this:

    <FormsyText
      name="name"
      defaultValue={someobject.name}
      validations={this.nameValidations(someobject, someobjects)}
      validationErrors={this.state.touched && this.nameValidationErrors()}
      onBlur={(e) => this.updateSomeObject({...someobject, name: e.target.value})}
    />
