### ISSUE TITLE
Google Places/Geocomplete Input?

### ISSUE THREAD

**Issue by acomito** [mbrookes/formsy-material-ui#122]
Is anyone aware of a formsy-material-ui option for a geocomplete?

a `<FormsyGeoComplete>` would be awesome

I'm looking at https://github.com/ubilabs/react-geosuggest

It looks like this has been suggested before: https://github.com/ubilabs/react-geosuggest/issues/69

**Comment by mbrookes** [comment]
@acomito This library is specifically for validation of Material-UI form fields using formasy-react, so.. no. 😄 

What I _think_ you're asking for is a Material-UI version of https://github.com/ubilabs/react-geosuggest, i.e. that Material-UI AutoComplete supports retrieving suggestions from Google Maps Places API. 

That's something you'd need to write as a wrapper for AutoComplete.
