### ISSUE TITLE
Components question 

### ISSUE THREAD

**Issue by bteepell** [mbrookes/formsy-material-ui#124]
Great repo.  Are you planning on adding more components.  Like chip and dropdown?  And maybe a multi select.

**Comment by mbrookes** [comment]
Only form components need formsy-react.

**Comment by bteepell** [comment]
The reason I asked is to help out with a multi select.  I have a select list of values that the users can add and remove from the list.   When I open my form i populate with the values it has already. I then provide a selection excluding what was previously selected.  So you can change the list before submit.  Chips seems to be the obvious choice as they can be delete and I can add from my selection list.

**Comment by mbrookes** [comment]
Sorry, still not sure what this has to do with formsy-react / formsy-material-ui.
