### ISSUE TITLE
Firefox required on FormsyText

### ISSUE THREAD

**Issue by bteepell** [mbrookes/formsy-material-ui#127]
First - Great library, I was looking at doing the same thing and glad I found this.  
Second - Question about Firefox.  I have a form with a few text fileds.  In chrome and IE they show up fine but in Firefox the Fields with required attribute show up with red around my multiLine? Anyone else seen this?
   <FormsyText id='Name' key="Name'
                        name="Name"
                        floatingLabelText="Name"
                        floatingLabelFixed={true}
                        hintText="Name (Required)"
                        required
                        validations={{maxLength:255}}
                        validationErrors={{maxLength}}
                         multiLine={true}
                       />

**Comment by semiautomatix** [comment]
How was this resolved? I'm getting it on all required fields.

**Comment by krzykrucz** [comment]
Same as above.

**Comment by rojobuffalo** [comment]
It's a default CSS rule applied by Firefox with the selector `:-moz-ui-invalid:not(output)`. Override with `box-shadow: none`
