### ISSUE TITLE
Update formsy-react version to 0.17.0

### ISSUE THREAD

**Issue by vijayrawatsan** [mbrookes/formsy-material-ui#14]

**Comment by mbrookes** [comment]
packages.json already allows formsy-react 0.17:

```
  "peerDependencies": {
    "formsy-react": ">=0.14.1 <1"
  },
```
 You just have to specify it in your parent project. If we force a dependancy on 0.17 here, it prevents the use of React 0.13.x, and not everything supports React 0.14 yet.

**Comment by vijayrawatsan** [comment]
Yep. Forgot to see that. :+1:
