### ISSUE TITLE
specify date format

### ISSUE THREAD

**Issue by morenoh149** [mbrookes/formsy-material-ui#140]
my api requires dates submitted in `YYYY[-MM[-DD]]` or `yyyy-mm-dd` format. How can I tell the `FormsyDate` component what format to store the date in?

I see some references to a `formatDate` prop https://github.com/mbrookes/formsy-material-ui/search?utf8=%E2%9C%93&q=formatdate&type=Issues but it's not in the docs

**Comment by morenoh149** [comment]
actually I think I can simply format the value returned from the input before submitting to the api instead.

**Comment by mbrookes** [comment]
Any props supported by Material-UI are passed through, incuding `formatDate`.
