### ISSUE TITLE
Support matchRegexp

### ISSUE THREAD

**Issue by morenoh149** [mbrookes/formsy-material-ui#141]
I'm trying to display an error when an input does not pass [matchRegexp](https://github.com/christianalfoni/formsy-react/blob/168521e5780bb4c2f0910bd307f1c3fb5f4419a7/API.md#validators) validation. Does formsy-material-ui support this?

**Comment by mbrookes** [comment]
It supports whatever formsy-react does...

**Comment by morenoh149** [comment]
perhaps I'm not using it correctly? I did

```
              <FormsyText
                name="dispense_as_written"
                floatingLabelText="Dispense as written"
                validation={{ matchRegexp: /foo/ }}
                required
              />
```
and indeed the validation is in effect because the submit button is disabled but I'm not seeing an error text near the input as I'd expect.

**Comment by codeaholicguy** [comment]
@morenoh149 currently, the value is only updated when you blur out of the `FormsyText`, if you want it update immediately, take a look at https://github.com/mbrookes/formsy-material-ui/pull/109

**Comment by morenoh149** [comment]
@mbrookes thoughts on cutting a new release?

**Comment by morenoh149** [comment]
the problem was I was missing the `validationError` prop. So the solution is
```
 <FormsyText
                name="foo_bar"
                floatingLabelText="foo bar"
                validation={{ matchRegexp: /foo/ }}
                validationError="Field must be foo"
                required
              />
```
