### ISSUE TITLE
Warning: Unknown prop `updateImmediately` on <input> tag. Remove this prop from the element.

### ISSUE THREAD

**Issue by lookapanda** [mbrookes/formsy-material-ui#144]
```
<FormsyText
    name="password"
    required
    floatingLabelText="Password"
    type="password"
    updateImmediately
    fullWidth={true}
/>
```

I get the error:

> Warning: Unknown prop `updateImmediately` on `<input>` tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in input (created by TextField)
    in div (created by TextField)
    in TextField (created by FormsyText)
    in FormsyText (created by Login)
    in div (created by Login)
    in form (created by Formsy)
    in Formsy (created by Login)
    in div (created by Login)
    in div (created by Login)
    in div (created by Login)
    in Login (created by RouterContext)
    in MuiThemeProvider (created by App)
    in App (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider

**Comment by codeaholicguy** [comment]
@lookapanda did you use directly from github? The code with`updateImmediately` prop has not been pushed to npm yet.

**Comment by lookapanda** [comment]
That explains a lot. Will try out the github version then :) Thanks!
