### ISSUE TITLE
Support material-ui@0.16.x

### ISSUE THREAD

**Issue by rojobuffalo** [mbrookes/formsy-material-ui#145]
Material UI v0.16 landed on Oct 3.

**Comment by Patrik-Glendell** [comment]
status on this ?

**Comment by joelkoz** [comment]
FYI, I reviewed the changes in Material UI from 0.15 to 0.16, and I didn't see any changes that should affect this project.  I am using formsy-material-ui without any issues (with the exception of the pull requests I've already made), so I think this is a simple matter of updating the dependencies in package.json to the new version of materia-ui

**Comment by rojobuffalo** [comment]
Closed by #157
