### ISSUE TITLE
Cannot resolve module

### ISSUE THREAD

**Issue by EngineerDiab** [mbrookes/formsy-material-ui#146]
Module not found: Error: Cannot resolve module 'formsy-material-ui/lib' in /usr/src/app/src/components

I see it in my node_modules, what is wrong?

**Comment by codeaholicguy** [comment]
What code you use for import `formsy-material-ui`? `import {FormsyText} from 'formsy-material-ui/lib'`, isnt it?

**Comment by EngineerDiab** [comment]
yeah I used that. it couldn't find the library in node_modules folder

**Comment by codeaholicguy** [comment]
I think there was some error when your code was built, could you please run `npm run build` and show me the result?

**Comment by EngineerDiab** [comment]
Thanks for the help. It was an error on my end!
