### ISSUE TITLE
Request for tag v0.5.1

### ISSUE THREAD

**Issue by rojobuffalo** [mbrookes/formsy-material-ui#147]
Nice job on #109 . Having the `updateImmediately` option is helpful. Could we please tag it? Would v0.5.1 be ok or maybe v0.5.1-rc1?

By the way, this project is super helpful--thanks.

**Comment by mbrookes** [comment]
Sorry it's taken a while to get a release out - I'm in the middle of moving house right now, but as soon as things settle I'll get on it.

**Comment by psmarcin** [comment]
+1

**Comment by mbrookes** [comment]
Done, and published to npm. @codeaholicguy - could you let me have your nam username, and I'll add you as an owner.

**Comment by codeaholicguy** [comment]
@mbrookes my npm username is `codeaholicguy`

**Comment by mbrookes** [comment]
Hum, okay - I thought I tried that - I'll try again.

**Comment by mbrookes** [comment]
Done!
