### ISSUE TITLE
How to show input error message programmatically

### ISSUE THREAD

**Issue by kdichev** [mbrookes/formsy-material-ui#158]
I have an email field that I want to validate on submit click so on the click I do check if this is an email, if it is correct I can pass tru if not I get return false.

```
 _onClick = (props) => {
    var regex = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
     if (regex.test(this.state.emailInput))  
      {  
        console.log("success");
       // go to next page
      } else {
        console.log("invalid email address!"); 
        // trigger email input error message
      }
    } 
```

Do you guys have any ideas, tips?

**Comment by codeaholicguy** [comment]
@kdichev You can take a look in https://github.com/christianalfoni/formsy-react/blob/master/API.md#validations, use `validations` with regex and customize`validationErrors`
