### ISSUE TITLE
Support material UI 0.16

### ISSUE THREAD

**Issue by GinjiBan** [mbrookes/formsy-material-ui#167]
I got the following error when installing my modules : 

`npm WARN formsy-material-ui@0.5.2 requires a peer of material-ui@^0.15.0 but none was installed.
`
Using material-ui@0.16.4

**Comment by Hotell** [comment]
I guess this can be closed https://github.com/mbrookes/formsy-material-ui/commit/7498119e9f660f6d7b9c63f32449baadc4954f1a
