### ISSUE TITLE
Formsy TextArea

### ISSUE THREAD

**Issue by GO345724** [mbrookes/formsy-material-ui#176]
Do we have formsy textarea components?

**Comment by joelkoz** [comment]
The FormsyText component has a "multiline=true" attribute you can use.

**Comment by rojobuffalo** [comment]
Formsy handles form logic. The material-ui component library is its own thing. This project bridges those two projects so that they work together smoothly. 

The thing you're asking about is the material-ui component library: Those docs are here: http://www.material-ui.com/#/components/text-field.
