### ISSUE TITLE
AutoComplete unknown props `validationError`, `validationErrors`

### ISSUE THREAD

**Issue by ddela-cr** [mbrookes/formsy-material-ui#177]
Hi, this code produces the following error : 

> Warning: Unknown props `validationError`, `validationErrors` on <input> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
>     in input (created by TextField)
>     in div (created by TextField)
>     in TextField (created by AutoComplete)

```
<FormsyAutoComplete
	name='userId'
	floatingLabelText="How often do you?"
	dataSource={this.state.users}
	dataSourceConfig={sourceConfig}
/>
```

I tried with AutoComplete from material-ui, it works fine

**Comment by weits** [comment]
Did you resolve it somehow? I have exactly the same issue ...

**Comment by ddela-cr** [comment]
apparently #119 fixes it but still errors, let me know if you find a fix

**Comment by ddela-cr** [comment]
@weits have you figured out a fix?

**Comment by ddela-cr** [comment]
[this issue](https://github.com/christianalfoni/formsy-react/issues/409) should fix the issue. Please update formsy-react dependency to 0.18.1

**Comment by weits** [comment]
I use just selects until it is fixed. My formsy-react is at version 0.18.1 so I doubt it will help.

**Comment by Casy** [comment]
any solution??

**Comment by rojobuffalo** [comment]
Was this a dup of #183? I think #184 fixes this.

**Comment by rojobuffalo** [comment]
Please re-try with latest v0.5.4

**Comment by yourse1f-yourorg** [comment]
I have been evaluating (trying to get started with) formsy-material-ui, and hit this error simply trying to run the [webpack example](https://github.com/mbrookes/formsy-material-ui/tree/master/examples/webpack-example)

I upgraded `package.json` with 

    "formsy-react": "^0.18.1",
    "formsy-material-ui": "^0.5.4",

**Comment by advance512** [comment]
The example supplied by the project doesn't work. Doesn't make you feel very sure about choosing formsy-material-ui as your forms library, does it..

**Comment by massile** [comment]
Any update on this ?
