### ISSUE TITLE
How to show required message after submit?

### ISSUE THREAD

**Issue by sambomartin** [mbrookes/formsy-material-ui#179]
Hi, I have a formsy-mui form, a text box. 

`  <FormsyText
                floatingLabelText="Name" required name="Name" style={fieldStyle} 
                />`

How to I get the text box to show an error if it's a required field thats not been entered?

I can get the regex working (immediately updating) but not submit validation

thanks
Sam

**Comment by astonm** [comment]
I believe this was fixed by #105, but it hasn't made it to npm yet.

**Comment by LordBastor** [comment]
@sambomartin Did you manage to get this to work in any way?

I'm trying to setup some regex to just make the required error appear somehow, but it doesn't seem to be working. Cheers.
