### ISSUE TITLE
Date-Picker slow performance

### ISSUE THREAD

**Issue by funkybunky** [mbrookes/formsy-material-ui#18]
After opening the modal of FormsyDate, there is a ~1s delay until the date-picker becomes responsive.
Also after clicking on a date, there is another ~1s delay until the corresponding date gets shown as text in modal header (example: clicking on 13, wait, "Fri,Nov 13" is shown in the header)
Any ideas what could cause these delays/ performance issues?

**Comment by mbrookes** [comment]
How well does the Material-UI date picker perform on the same system outside of Formsy / fmui? The date picker is slow, but not that slow! Try setting an explicit date range.

**Comment by funkybunky** [comment]
I set the date range smaller (14months) and the picker now performs quite well. Thanks!
If you accept it, I would make a PR and add it to the readme (perhaps under "Known Issues"?) and even update the example code accordingly. Are you okay with that?

**Comment by mbrookes** [comment]
Well, it isn't an issue with formsy-material-ui per-se, so not sure it belongs in issues, but it would be a good idea to update the example since this is an undocumented best practice for Material-UI, and a code comment could highlight the issue. You might like to update the MAterial-UI docs too! :wink:

**Comment by funkybunky** [comment]
Given the perf fixes from https://github.com/callemall/material-ui/pull/1905, should we still update the examples to include a reduced date-range? I had the impression that it doesn't affect it noticeably with this perf fix in place.

**Comment by mbrookes** [comment]
No, lets leave the example as is. Glad you go it resolved.
