### ISSUE TITLE
FormsyAutoComplete not update after select a result

### ISSUE THREAD

**Issue by Stupidism** [mbrookes/formsy-material-ui#183]
![image](https://cloud.githubusercontent.com/assets/5801015/20919002/aa1015e4-bbd4-11e6-915e-6522853950bf.png)

Look at the auto-complete field. I typed `s` and selected `Weeknights`, but the result after submit is still `s`

**Comment by rojobuffalo** [comment]
I merged the PR for the Autocomplete component without thoroughly reviewing it. That was my mistake. What does your code for using that component look like?

**Comment by VanessaRLewis** [comment]
I experience the same problem when running the sample webpack SPA.

**Comment by Stupidism** [comment]
This is the webpack-example inside the repo. @rojobuffalo

**Comment by Stupidism** [comment]
I added onNewRequest, searchText and value props to use it as a controlled component. You can use this as a temp solution before it's fixed.

**Comment by Casy** [comment]
can we fix this now? @rojobuffalo

**Comment by rojobuffalo** [comment]
I think we just fixed this with #184
