### ISSUE TITLE
ERROR during build in examples

### ISSUE THREAD

**Issue by stereoit** [mbrookes/formsy-material-ui#189]
Hi, I am getting errors:

`ERROR in ./~/react-tap-event-plugin/src/injectTapEventPlugin.js
Module not found: Error: Cannot resolve module 'react/lib/EventPluginHub' in /home/rsmol/Code/git/formsy-material-ui/examples/webpack-example/node_modules/react-tap-event-plugin/src
 @ ./~/react-tap-event-plugin/src/injectTapEventPlugin.js 23:2-37
`
during the build of the webpack-example module. I've tried to do yarn upgrade, but no luck either.

**Comment by rojobuffalo** [comment]
I think we just fixed this with #187.
