### ISSUE TITLE
Create v0.5.4 and push to NPM 

### ISSUE THREAD

**Issue by astonm** [mbrookes/formsy-material-ui#190]
There are a bunch of PRs that have been pulled in since the last release was cut in November, and it would be nice to be able to use some of the new functionality and fixes.

I checked with @rojobuffalo and @mbrookes, it seems like you have the power to make this so?

**Comment by rojobuffalo** [comment]
I agree that it would be good to tag a new version. Just to be clear, I don't have permission to do that. FYI, if you're in a pinch you can use `npm install mbrookes/formsy-material-ui` to install from the master branch.

https://docs.npmjs.com/cli/install

**Comment by jolan** [comment]
I'm trying to just use it from git but that has devolved into learning how to get webpack/babel to load/transpile src/*.jsx and failing miserably.

Pretty please, release an update.

**Comment by astonm** [comment]
@jolan you can run `npm run prepublish` (or really, `npm run build`) to transpile the files, or if you want `npm install` to do it for you (say as part of a deploy), you can clone the repo locally and then run `npm install path/to/local/checkout` which will cause `npm` to run `prepublish`. Why `npm install` ends up running `prepublish` on locally defined packages and NPM packages but not ones from GitHub is the subject of a very [long discussion](https://github.com/npm/npm/issues/3055).

**Comment by jolan** [comment]
Thanks, I ended up doing just that -- cloned the repo, transpiled, added the lib directory to my fork, and pointed there.

**Comment by rojobuffalo** [comment]
Just tagged v0.5.4 on GitHub but don't have access to publish to npm. @mbrookes would you consider [adding another npm owner](https://docs.npmjs.com/cli/owner)?

**Comment by mbrookes** [comment]
@rojobuffalo Glad to - just not on the right machine at the moment. 

Would you mind adding the changes to the changelog? I had been trying to credit the PR author, and it would probably be even better to also include the PR #, but as much as you care to do. Not for me to dictate at this stage!!!

**Comment by mbrookes** [comment]
> but don't have access to publish to npm.

You sure? I just double-checked, and you're already a maintainer on NPM...

**Comment by rojobuffalo** [comment]
Hot damn! Didn't realize that I had been given permission for that. Thanks.
