### ISSUE TITLE
Very poor performance

### ISSUE THREAD

**Issue by Seke1412** [mbrookes/formsy-material-ui#191]
The latest version 0.5.4 have a very poor performance while checking and validating form (onChange event). It works fine on 0.5.3 and backwards

**Comment by scrambled2k3** [comment]
I am seeing this as well.  Using FormsyText, if you type into the input field some letters get missed unless you type really slowly.
```
<FormsyText
    floatingLabelText="Description"
    required
    name={"description"}
    updateImmediately
    defaultValue={item.ItemDescription}
    onChange={this.handleChecklistItemChange.bind(this)}
    validationErrors={language.validationErrors}
/>
```

**Comment by rojobuffalo** [comment]
I probably merged something that I shouldn't have. Looking into it now.

**Comment by rojobuffalo** [comment]
#192 reverts these breaking changes. I just tagged and released v0.5.5 so @latest should be stable.

**Comment by protoEvangelion** [comment]
@rojobuffalo I'm noticing some bad lag when typing into a FormsyText field using v0.5.5.  Are you experiencing something similar?

**Comment by rojobuffalo** [comment]
I'm not getting that anymore. Do you have a screenshot video or some code samples?

**Comment by protoEvangelion** [comment]
I think it was an issue with my CPU because it is working fine now :)
