### ISSUE TITLE
Flawed example : "Warning: Unknown prop `menuItems` on <div> tag"

### ISSUE THREAD

**Issue by martinhbramwell** [mbrookes/formsy-material-ui#193]
When running the example app, I get : 

    Warning: Unknown prop `menuItems` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
        in div (created by TextField)
        in TextField (created by SelectField)
        in SelectField (created by FormsySelect)
        in FormsySelect (created by Main)
        in form (created by Formsy)
        in Formsy (created by Main)
        in div (created by Paper)
        in Paper (created by Main)
        in MuiThemeProvider (created by Main)
        in Main

Removing [line 100](https://github.com/mbrookes/formsy-material-ui/blob/master/examples/webpack-example/src/app/Main.js#L100) makes the warning go away, without reducing normal functionality.

Is there some non-obvious reason for that line to be there?

**Comment by rojobuffalo** [comment]
I think that is a carry over from an older API. Now the menu items are passed in as children, but before I think they were passed in an array to that prop. Looks like that line should be removed. Feel free to submit that as a PR.
