### ISSUE TITLE
FormsySelect not working properly on 0.5.5

### ISSUE THREAD

**Issue by SystemPanic** [mbrookes/formsy-material-ui#195]
FormsySelect changes to wrong value.

Example code: 

```
<FormsySelect
name="somename"
floatingLabelText="Some"
floatingLabelFixed={true}
value={this.state.some}
required
onChange={(event, index, value) => {this.setState({some: value})}}>
	<MenuItem value={1} primaryText="Some value 1" />
	<MenuItem value={2} primaryText="Some value 2" />
</FormsySelect>
```

**Comment by SystemPanic** [comment]
Is just onChange incorrect params ordering, works when change the order (event, value, index)

On Material-UI docs, onChange for SelectField is (event, index, value), so fix when possible or say in documentation.

**Comment by mbrookes** [comment]
@SystemPanic It does say in the the docs: https://github.com/mbrookes/formsy-material-ui#events

Unfortunately Material-UI was slow to adopt that proposal.
