### ISSUE TITLE
Is Material-ui 1.0 alpha supported?

### ISSUE THREAD

**Issue by CarlosV89** [mbrookes/formsy-material-ui#201]
Im getting this error when I try to use it, is there another version that has correct bindings for that version of material-ui?
```
 in ./~/formsy-material-ui/lib/FormsySelect.js
 Module not found: Error: Can't resolve 'material-ui/SelectField' in '/Users/cvillalta/Proyects/admin8/node_modules/formsy-material-ui/lib'
  @ ./~/formsy-material-ui/lib/FormsySelect.js 17:19-53
```

**Comment by rojobuffalo** [comment]
Material UI 1.0 is still on alpha release. We're not going to chase supporting those quick iteration tags. Let's re-open when a stable version gets released.
