### ISSUE TITLE
File picker?

### ISSUE THREAD

**Issue by cristianocca** [mbrookes/formsy-material-ui#203]
What's the right way to build a file picker with this?
I haven't found anything so I'm using a File component from formsy-react-components but it doesn't go well with material-ui clearly.

**Comment by mbrookes** [comment]
The Material-UI docs have an example of an input wrapped with a button as a file input: http://www.material-ui.com/#/components/flat-button, you could perhaps build on that with the formsy-material-ui input?

**Comment by cristianocca** [comment]
I was expecting that to be implemented as part of formsy-material-ui just like the other basic inputs, so all the labels, error messages, and validation is performed without the need to manually do all of it.
Trying with the formsy-react-components <File/> somehow works but all the error and label styles are not material.

With what you suggest, would it easily integrate with all the formsy-material-ui props such as required, validators, errors (in red below following material design styles) and such and form validation? I guess I need to build all components together from both formsy and material-ui to get the same look and feel of the other formsy components.

I will give it a shot I guess.

**Comment by mbrookes** [comment]
@cristianocca Please understand that formsy-material-ui is just a compatibility wrapper for Material-UI form component. Material-UI doesn't provide a file component (beyond the example I linked to), so neither does this library.
