### ISSUE TITLE
requiredError on FormsySelect

### ISSUE THREAD

**Issue by ulich** [mbrookes/formsy-material-ui#204]
When I try to add the `requiredError` prop on a `FormsySelect`, I get this error:

```
Warning: Unknown prop `requiredError` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by TextField)
    in TextField (created by SelectField)
    in SelectField (created by FormsySelect)
    in FormsySelect (at ProductFormPage.js:82)
```

I think the problem is that the `requiredError` prop is not declared here: https://github.com/mbrookes/formsy-material-ui/blob/master/src/FormsySelect.jsx#L45, thus it is in `{...rest}`, which is then passed down to `SelectField` etc.

**Comment by mbrookes** [comment]
@ulich Are you able to try #205 ? (I edited it in the browser, so haven't tested).

**Comment by ulich** [comment]
thanks for the fast fix!
