### ISSUE TITLE
Red box encircling the required fields on firefox

### ISSUE THREAD

**Issue by Vishal0203** [mbrookes/formsy-material-ui#207]
There is an issue with required fields. Attaching a snapshot. 

![screen shot 2017-04-12 at 5 56 56 pm](https://cloud.githubusercontent.com/assets/8856973/24957475/7673cbc0-1fa9-11e7-9373-015163fb4648.png)

**Comment by mbrookes** [comment]
Dupe of #127

**Comment by Vishal0203** [comment]
@mbrookes thanks that solves
