### ISSUE TITLE
Setting defaultValue still shows hint/floatingLabelText

### ISSUE THREAD

**Issue by sys13** [mbrookes/formsy-material-ui#21]
I'm trying to show a defaultValue. However, if hintText or floatingLabelText is set they will overlay over the defaultValue. 

Using these versions:
```
"material-ui": "0.13.1",
"formsy-react": "0.17.0",
"formsy-material-ui": "0.2.4",
```

**Comment by mbrookes** [comment]
@vijayrawatsan - looks like this was introduced in 0.2.3, and remains in 0.2.4. Could you take a look please when you get a chance? Thanks.

**Comment by vijayrawatsan** [comment]
@sys13 how are you setting defaultValue can you give me an example. I will try that example with 2.2 2.3 and 2.4.
Will try to figure out what changed. Can't commit to work on this asap as I am running on some deadlines. But will surely run this on my background thread :wink:

**Comment by mbrookes** [comment]
Something like:
```jsx
<FormsyText
  name='url'
  validations='isUrl'
  validationError="Please provide a valid URL"
  defaultValue="http://"
  hintText="http://www.example.com"
  floatingLabelText="URL" 
/>
```

**Comment by mbrookes** [comment]
Hi Daniel, Please could you try the version in this branch: https://github.com/mbrookes/formsy-material-ui/tree/textfield-dafaultValue ? 

You will need to use <FormsyText value="Default value" />.

Formsy and Material-UI use `value` to mean different things, and the Formsy mixin expects the default value to be on the `value` prop. Hope this sort out the issue!

Vijay, any thoughts?

**Comment by sys13** [comment]
Sorry, how do I run this locally?

**Comment by mbrookes** [comment]
Like this: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies (or similar, depending on how you deploy NPM packages).

**Comment by sys13** [comment]
Having trouble installing it. I tried using this line in my packages.json file:
```
"formsy-material-ui": "https://github.com/mbrookes/formsy-material-ui/archive/0ee888be254a2ff8cd778eec51d2ea69e918b451.tar.gz",
```
but I got this error
```
error: couldn't install npm package
   formsy-material-ui@https://github.com/mbrookes/formsy-material-ui/archive/0ee888be254a2ff8cd778eec51d2ea69e918b451.tar.gz:
   Command failed: npm WARN package.json react-addons-create-fragment@0.14.2 No
   repository field.
   npm WARN package.json react-addons-pure-render-mixin@0.14.2 No repository
   field.
   npm WARN package.json react-addons-transition-group@0.14.2 No repository
   field.
   npm WARN package.json react-addons-update@0.14.2 No repository field.
   npm ERR! fetch failed
   https://github.com/mbrookes/formsy-material-ui/archive/0ee888be254a2ff8cd778eec51d2ea69e918b451.tar.gz
...
...
...
```

**Comment by mbrookes** [comment]
```
npm ERR! fetch failed
https://github.com/mbrookes/formsy-material-ui/archive/0ee888be254a2ff8cd778eec51d2ea69e918b451.tar.gz
```

Not sure what that hash is, but it isn't from this repo!

Try: 

```
"formsy-material-ui": "https://github.com/mbrookes/formsy-material-ui/archive/18a0e9be71fcec019f3add2a51535b8823d7e465.tar.gz",
```

**Comment by sys13** [comment]
Thanks for the link. And it works great using the ```value``` prop. Also, I am no longer having an issue where it was requiring me to give focus to all required fields. Much appreciated.

**Comment by mbrookes** [comment]
0.2.5 published.
