### ISSUE TITLE
Support latest versions of formsy-react@^0.19.2 and material-ui@^0.18.0

### ISSUE THREAD

**Issue by mjsevilla** [mbrookes/formsy-material-ui#216]
`formsy-material-ui@0.6.0 UNMET PEER DEPENDENCY material-ui@0.18.0`
`npm WARN formsy-material-ui@0.6.0 requires a peer of material-ui@^0.17.0 but none was installed.`

**Comment by hashwin** [comment]
Hi @mbrookes, any update on this?

**Comment by rojobuffalo** [comment]
This will be a top priority for tagging a new release this week.
