### ISSUE TITLE
FormsyDate endless render loop on IE 11

### ISSUE THREAD

**Issue by cristianocca** [mbrookes/formsy-material-ui#218]
`<FormsyDate
name="somename"
value={this.props.someDefaultValue}
/>`

When the above is used within a form, it causes the component that renders the form and the above to endlessly call to render when using IE 11. 

I'm not sure if this is an issue with the implementation of FormsyDate or the actual Formsy-React component that it uses.

Edit: using: 
"formsy-material-ui": "^0.6.0"
"formsy-react": "^0.19.2"

I think this didn't happen with 0.5.5

**Comment by rojobuffalo** [comment]
@cristianocca Did you try isolating the Formsy-React component to see if that's were the issue is coming from?

**Comment by cristianocca** [comment]
Yes, no issues with just the material ui picker.


-------- Mensaje original --------
De: Ryan Blakeley <notifications@github.com>
Fecha: 18/7/17 19:07 (GMT-03:00)
Para: mbrookes/formsy-material-ui <formsy-material-ui@noreply.github.com>
Cc: Cristiano Coelho <cristianocca@hotmail.com>, Mention <mention@noreply.github.com>
Asunto: Re: [mbrookes/formsy-material-ui] FormsyDate endless render loop on IE 11 (#218)


@cristianocca<https://github.com/cristianocca> Did you try isolating the Formsy-React component to see if that's were the issue is coming from?

**Comment by rojobuffalo** [comment]
Hmm, did you try with `v0.6.1` that I published today? I didn't work on it but there might have been an incidental fix..?

**Comment by cristianocca** [comment]
I can't really test anymore since this was some time ago and the code was changed and is no longer an issue.


-------- Mensaje original --------
De: Ryan Blakeley <notifications@github.com>
Fecha: 19/7/17 20:11 (GMT-03:00)
Para: mbrookes/formsy-material-ui <formsy-material-ui@noreply.github.com>
Cc: Cristiano Coelho <cristianocca@hotmail.com>, Mention <mention@noreply.github.com>
Asunto: Re: [mbrookes/formsy-material-ui] FormsyDate endless render loop on IE 11 (#218)


Hmm, did you try with v0.6.1 that I published today? I didn't work on it but there might have been an incidental fix..?

**Comment by rojobuffalo** [comment]
Ok, no problem.
