### ISSUE TITLE
propTypes of Validations and ValidationErrors

### ISSUE THREAD

**Issue by lethanhquang** [mbrookes/formsy-material-ui#24]
propTypes of Validations and ValidationErrors should be oneOf string or object.

**Comment by mbrookes** [comment]
Actually, given that the majority of props are just passed through to formsy-react or material-ui, where they are presumably already type checked, I"m not sure how much value there is in having them duplicated here, so I'd be happy to remove any we don't directly consume.

What do you think?

**Comment by mbrookes** [comment]
Removed in 0.3.0.
