### ISSUE TITLE
Problem with `v0.3.0` NPM package

### ISSUE THREAD

**Issue by py-in-the-sky** [mbrookes/formsy-material-ui#26]
I npm installed twice to update to v0.3.0, and the package only contained the following:

* CHANGELOG.md
* LICENSE
* package.json
* README.md

**Comment by mbrookes** [comment]
Huh, you're right! Try now.

**Comment by py-in-the-sky** [comment]
That did the trick!  Thanks!

**Comment by mbrookes** [comment]
Cool. Sorry for the inconvenience!
