### ISSUE TITLE
[FormsyText] visual feedback for required inputs

### ISSUE THREAD

**Issue by cbioley** [mbrookes/formsy-material-ui#28]
Hi,

Apparently, setting the `required` attribute on a `FormsyText` reports the form state as invalid (the submit button can be disabled), but no message appears below the field? Is it the expected behavior? Shouldn't we do something with the `showRequired` function?

**Comment by mbrookes** [comment]
MUI doesn't have a built in indicator for required fields (an asterisk or such), so we would either have to reuse errorText, or add an indicator of our own to the MUI component.

Using the errorText would work for forms that _don't_ disable the submit button, as the error could be displayed on submit, although arguably that's not great UX, as the user wouldn't know what was required vs optional until after trying to submit.

For forms with the submit button disabled when invalid you can't display an error after submit, (since you can't submit until the form is valid :laughing:). However it might be a bit obtrusive if "This field is required" (or whatever message) was displayed under every required field before the form has even been completed, so a separate indicator might be preferable.

**Comment by sys13** [comment]
I've just been adding an asterisk to my floating name/hint text.

Matt Brookes <notifications@github.com> 於 2015年11月14日 週六 上午1:43 寫道：

**Comment by mbrookes** [comment]
Yeah, I was just thinking the same thing, so had gone to look at the Material Design spec [1]  to see if there were any hints as to the preferred approach.

The only thing I could find was in "Multi-line text field", which has "(optional)" after the floatingLabelText. We _could_ automate that, but how hard is it to add that to your (un)required fields, or "(required)" or "*" to your required ones...? 

Which then just leaves whether to use errorText to reinforce that for forms that don't disable the submit button, if the user still tries to submit a form with required fields not filled in.

[1] https://www.google.com/design/spec/components/text-fields.html#text-fields-floating-labels

**Comment by cbioley** [comment]
> Which then just leaves whether to use errorText to reinforce that for forms that don't disable the submit button, if the user still tries to submit a form with required fields not filled in.

I don't know, but I have the feeling that a required field should be emphasised with more than a little "*", because it's so easy to miss. Very frustrating if you can't submit and your only resort is to guess (of course, I'm talking about forms with a lot of inputs). 

This kind of feedback does seem right to me: https://infinit.io/_/qcDMnYN

**Comment by mbrookes** [comment]
> I don't know, but I have the feeling that a required field should be emphasised with more than a little "*", because it's so easy to miss.

So use "(required)" instead.

**Comment by cbioley** [comment]
I agree with you that required fields should not display an error *before* a submit.

Problem is I can't see the error message ("this field is required") below the field after the first attempt to send the data.

**Comment by mbrookes** [comment]
> I agree with you

Cool. Happy to take a PR for this feature. Suggest to make it optional, depending on the presence of a 'requiredError' string prop.

**Comment by mbrookes** [comment]
The December update of Material Design has clarified handling required fields:

https://www.google.com/design/spec/components/text-fields.html#text-fields-required-fields

So, an asterisk it is... which contradicts some of the examples elsewhere in the spec, and in google's own apps, but the MD spec is nothing if not inconsistent!

**Comment by jackyon** [comment]
hi @mbrookes, when can we start to use the 'requiredError' string prop?

**Comment by mbrookes** [comment]
@jackyon When someone contributes a PR. 👍

**Comment by jackyon** [comment]
sorry, I already switch to using redux form, it plays well with material-ui
