### ISSUE TITLE
Validation breaks when setting initial state.

### ISSUE THREAD

**Issue by mvandiest** [mbrookes/formsy-material-ui#3]
Maybe there is some other way to do this, but I'm having the following problem...

Using `valueLink` breaks validation as it does not go through formsy's getValue() behavior. If you attempt to pass a `value` prop, as you normally would with formsy, then that prop is spread down to the material-ui component and bypasses formsy's getValue() behavior as well.

I'm in a crunch so I don't have time to make a PR, but I've proven, at least for FormsyText that the following example using destructuring works:

```
let FormsyText = React.createClass({
  mixins: [ Formsy.Mixin, FormComponentMixin ],
  render: function() {
    var { value, ...other } = this.props;
    return (
      <TextField
        value={this.getValue()}
        {...other}
        onChange={this.handleChange}
        errorText={this.getErrorMessage()} />
    );
  }
});
```

I don't know whether the same destructuring can be used for the other fields. But I thought I'd start a dialog here around this problem.

**Comment by mbrookes** [comment]
I have to confess I hadn't come across valueLink - it doesn't appear to be documented other than appearing in a couple of examples. 

The only form components that support it are textfield, datepicker, checkbox and toggle (and also textarea / enhanced-textarea, but both of those are completely undocumented, so not sure if they're supported features, so aren't included in this library yet).

If you would like to test your fix in those other three, I would be happy to accept accept a PR when you have the opportunity.

**Comment by mbrookes** [comment]
Hi @mvandiest - can you try this again now that FormsyText is rewritten, and value is supported for passing a default value to Textfield via Formsy validation?

**Comment by mvandiest** [comment]
Hey @mbrookes, sorry for the delay. So, I pulled the 0.3.2 in to my local demo and the value property works perfectly now. So, this issue can be closed. I'm not really sure which PR to attribute the fix to since there's been a lot of mods over the last month.

**Comment by mbrookes** [comment]
#23 / 0.2.5 I think. :)
