### ISSUE TITLE
dynamically add/remove form field

### ISSUE THREAD

**Issue by tnrich** [mbrookes/formsy-material-ui#32]
Hey there, I'm wondering if you know of an easy way to add/remove form fields depending on the state of the form. For example, showing a new section of the form if a user selects a certain checkbox. 

Thank you!

**Comment by mbrookes** [comment]
There's an example in the formsy-react repo: https://github.com/christianalfoni/formsy-react/tree/master/examples/dynamic-form-fields

I haven't tried it with formsy-material-ui, so let me know how you get on. If there's anything that FMUI breaks, let me know and I'll look into it.
