### ISSUE TITLE
Possibility to style the error message

### ISSUE THREAD

**Issue by maticrivo** [mbrookes/formsy-material-ui#33]
can we have the possibility to style the error message?
for instance sending a hintStyle objects styles the hint text, maybe we can have an errorStyle to style the error

**Comment by mbrookes** [comment]
Hi @maticrivo - sorry for the delay, I actually managed a few days away from the computer!  However I think you might have meant to post this over at material-ui? 

In the case of formsy-material-ui, you can pass any props that material-ui supports to the forrmsy-material-ui component, and they will be passed down (if not consumed by fmui itself), inclusing style props.

I didn't check all the components, but at least Textfield and SelectField support errorStyle. If one you need doesn't, please open an issue there, and I know PRs are always welcome.
