### ISSUE TITLE
Checkboxes don't toggle

### ISSUE THREAD

**Issue by STRML** [mbrookes/formsy-material-ui#35]
It appears the internal `switched` property (on MUI Checkbox) is no longer being toggled properly when wrapped in a `<FormsyCheckbox>`.

It appears that:

* A click calls `<EnhancedSwitch>`'s `_handleChange()`.
* This calls `this.props.onParentShouldUpdate()`, which is implemented by `<Checkbox>` and calls `this.setState({switched: true})`.
* In the same callback, `<EnhancedSwitch>` also calls `this.props.onSwitch()`, which is implemented by `<Checkbox>`.
* `<Checkbox>` calls its own `onCheck` which is set by Formsy-MUI.
* This calls Formsy-MUI's `setValue()`, which fires another `setState()`.
* This causes the `<FormsyCheckbox>` to rerender, which fires `<Checkbox>`'s componentWillReceiveProps.
* `<Checkbox>`'s componentWillReceiveProps calls its own `setState()`, which looks at the value of `this.state.switched` and overwrites it. But it hasn't changed yet, the transition is still pending, so it is always set to `false`.

Not sure what the fix is here. `<EnhancedSwitch>` should probably be passing a callback to `onParentShouldUpdate()` that it can send to `setState()`, to ensure the state transition flushes before any other handlers fire.

**Comment by STRML** [comment]
Here's a photo showing `<Checkbox>` handling the cWRP callback, while the `switched: true` transition is still pending:

![](http://i.imgur.com/SFKTS05.jpg)

**Comment by mbrookes** [comment]
@STRML - thanks for the detailed report. Looks like something changed between 0.14.0-rc1 and 0.14.0-rc2. @alitaheri any thoughts?

**Comment by alitaheri** [comment]
We're planning to make all our components controllable with stateful wrappers to help with forms. There are indeed many problems regarding how state is handled. and we should not handle state at all! It's the user's concern how the data flows through their application. we shouldn't make assumptions! @STRML Whenever you get the time please open an issue in material-ui repository too. We should track these bugs Thanks :grin:... oh sorry I meant ( ^_^ )

**Comment by mbrookes** [comment]
> Thanks :grin:... oh sorry I meant ( ^_^ )

:grinning:

**Comment by STRML** [comment]
Great, thanks!

**Comment by mbrookes** [comment]
No worries. Can you test against master, and if all looks good for you, I'll push a new release.

**Comment by STRML** [comment]
:+1: Works here.
