### ISSUE TITLE
MUI 0.14.1 causes error: Warning: React.createElement: type should not be null, undefined, boolean, or number.

### ISSUE THREAD

**Issue by etmarch** [mbrookes/formsy-material-ui#36]
App info: Meteor 1.3 beta-latest, `formsy-react` and `formsy-material-ui` have been installed via the new Meteor modules syntax. When I am only using formsy-react (`<Formsy.Form />`) with a custom created input component, everything loads fine and no errors. 

However, as soon as I put ` <FormsyDate />` (or any of the other input types) nested into the Formsy.Form component, I get these errors on the client:

`Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of FormsyDate`. 

and `Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of FormsyDate`.
 
I am importing both modules into my current file like so:
```javascript
const Formsy = require('formsy-react');
const FMUI = require('formsy-material-ui');
const { FormsyCheckbox, FormsyDate, FormsyRadio, FormsyRadioGroup, FormsySelect, FormsyText, FormsyTime, FormsyToggle } = FMUI; 
``` 

I have tried everything to make these errors go away, but I've hit a wall for sure. Do you have any idea what could be causing these errors?

**Comment by mbrookes** [comment]
Are you by any chance using material-ui 0.14.1? If so there was a regression introduced by the change to babel 6. It will be fixed in 0.14.2, but I might put a workaround in formsy-material-ui in the meantime. For now, try material-ui 0.14.0.

If it isn't that, we'll have to take another look. I haven't tried Meteor 1.3 beta yet.

**Comment by etmarch** [comment]
Aha, so the culprit was material-ui 0.14.1 all along! After reverting to 0.14.0, the inputs display without any errors, thank you kindly. I seriously thought I was losing my mind for a second. 

Before I close this issue, do you think this regression should be mentioned in the ReadMe (until 0.14.2)?

**Comment by mbrookes** [comment]
Probably not a bad idea. You can leave this issue open for now too, until material-ui is fixed and / or formsy-material-ui has a workaround.

**Comment by etmarch** [comment]
Ok will do. Thanks again for your help.

**Comment by mbrookes** [comment]
[Material-UI 0.14.2]( https://github.com/callemall/material-ui/releases/tag/v0.14.2) released.
