### ISSUE TITLE
[FormsySelect] inconsistent behavior

### ISSUE THREAD

**Issue by mbrookes** [mbrookes/formsy-material-ui#4]
Often can't be selected by mouse, up/down keys don't cycle through selection when the dropdown isn't open.

**Comment by dmlinn** [comment]
Changing:
  handleChange: function (event) {
    this.setValue(event.currentTarget.value);
  },
to:
  handleChange: function (event) {
    this.setValue(event.target.value);
  },
fixes the issue with mouse selection. Apparently clicking on the span in the option returns with a currentTarget of null.

**Comment by mbrookes** [comment]
Nice, thanks!

**Comment by mbrookes** [comment]
Fixed by #13. Thanks!
