### ISSUE TITLE
Why can't we pass a defaultValue to formsy mui textfields?

### ISSUE THREAD

**Issue by tnrich** [mbrookes/formsy-material-ui#46]

**Comment by mbrookes** [comment]
You can, but as it says in the [README](https://github.com/mbrookes/formsy-material-ui#usage) you have to use value instead.

**Comment by tnrich** [comment]
Thanks for the link.
I was particularly wondering why Formsy-Mui didn't adhere to the MUI defaultValue prop? It seems like value and default value have different connotations.

**Comment by mbrookes** [comment]
https://github.com/mbrookes/formsy-material-ui/issues/21#issuecomment-154213340

**Comment by mbrookes** [comment]
Version on master now supports defaultValue. Let me know if it works for you.
