### ISSUE TITLE
Show off package quality

### ISSUE THREAD

**Issue by py-in-the-sky** [mbrookes/formsy-material-ui#51]
This project gets a [high score](http://packagequality.com/#?package=formsy-material-ui) on http://packagequality.com/, so why not show it off?

Here's [an example](https://github.com/erikras/redux-form#redux-form) of another project showing it off on the README.md.

**Comment by mbrookes** [comment]
Thanks for the pointer - I hadn't come across that one, but I should have looked at your example befre adding it - I assumed it would be a small badge "in the style of", but it's a bit big and showy-offy.

Take a look and see what you think, but I might revert that last commit.

**Comment by py-in-the-sky** [comment]
Ha!  It does stand out quite a bit.  I don't think it's gaudy, though, but my feelings wouldn't be hurt if you decide to forgo it.  :)

**Comment by mbrookes** [comment]
Thanks for the suggestion, but every time I saw it, the appearance of that badge rubbed me up the wrong way. :smile: If they change it we can happily revisit this!

**Comment by py-in-the-sky** [comment]
no problem!
