### ISSUE TITLE
Yellow frame made on double clicking FormsyText

### ISSUE THREAD

**Issue by dhruvdatt** [mbrookes/formsy-material-ui#52]
I recently started using material-ui and stumbled upon formsy-material-ui just what I needed.
I get this odd issue when selecting an option by double clicking a text field.There is a yellow box made around it.This does not go until I type something.Is this only my issue.How do I prevent it.
This issue is also in the live demo.

![odd](https://cloud.githubusercontent.com/assets/12109834/13283864/5f2f2ed8-db16-11e5-8324-2cabf3a4e302.png)

**Comment by mbrookes** [comment]
I'm guess this is in Chrome? That's it's indication that a form has been autofilled. This is neither a Material-UI not formsy-material-ui issue.

LMGTFY:  http://www.zigpress.com/2014/11/22/stop-chrome-messing-forms/

`input:-webkit-autofill { -webkit-box-shadow:0 0 0 500px white inset; }`
