### ISSUE TITLE
Text fields are laggy

### ISSUE THREAD

**Issue by ffxsam** [mbrookes/formsy-material-ui#54]
disregard. till I find a way to fix

**Comment by reohjs** [comment]
Hey, did you find a fix yet? + are you using the MuiThemeProvider component from material-ui v0.15.0-alpha.1?

**Comment by ffxsam** [comment]
I stopped using formsy altogether, actually. I plan on making my own lightweight add-on.

**Comment by mbrookes** [comment]
:+1: Look forward to seeing what you come up with. formsy-react looks like it might have come to the end of it's development, which doesn't bode well for formsy-material-ui!

**Comment by reohjs** [comment]
Ah, bummer... I solved it for now by removing the onChange & value props from the `FormsyText` file, seems to work fine (v0.3.5).

Thanks for bringing this to attention @mbrookes

**Comment by pilgrimtech** [comment]
@reohjs mind making a pull-request for this?

**Comment by reohjs** [comment]
@pilgrimtech [Done](https://github.com/mbrookes/formsy-material-ui/pull/72) :)
