### ISSUE TITLE
"Select Component" like "Select 2"?

### ISSUE THREAD

**Issue by thearabbit** [mbrookes/formsy-material-ui#56]
I used to use `select2` with `BS3`.
Have any `Select Component` for `this`?

**Comment by mbrookes** [comment]
`FormsySelect`. If you need more advanced features than Material-UI SelectField supports, feel free to contribute there.

**Comment by thearabbit** [comment]
Thanks, I can't help (new for react & material).
It mean `react select/combo`!

**Comment by mbrookes** [comment]
Not supported at the moment.
