### ISSUE TITLE
[FormsySelect] dropdown doesn't work

### ISSUE THREAD

**Issue by Jan-Jan** [mbrookes/formsy-material-ui#59]
Nothing happens when I click on a FormsySelect component. (Neither are there any errors/warnings/messages in the console.)

I created the FormsySelect component as per the README.md
```
      <FormsySelect
        name='frequency'
        required
        floatingLabelText="How often?">
        <MenuItem value={'never'} primaryText="Never" />
        <MenuItem value={'nightly'} primaryText="Every Night" />
        <MenuItem value={'weeknights'} primaryText="Weeknights" />
      </FormsySelect>
```

Please note FormsyText works as per the README. 

I am using
```
"formsy-material-ui": "^0.3.8",
"formsy-react": "^0.17.0",
"material-ui": "^0.14.4",
```

**Comment by mbrookes** [comment]
Here's a working example. It uses Meteor, but only as a handy way to deploy the demo site. Tee code is pure React.

https://github.com/mbrookes/formsy-mui-demo

**Comment by simpixelated** [comment]
Note, this is the key line from the demo that I was missing:
https://github.com/mbrookes/formsy-mui-demo/blob/master/Form.jsx#L3
```javascript
injectTapEventPlugin();
```

`FormsySelect` uses Material-UI `SelectField`, which requires react-tap-event-plugin.
https://github.com/callemall/material-ui#react-tap-event-plugin
