### ISSUE TITLE
onEnterKeyDown has been deprecated in material-ui 0.15

### ISSUE THREAD

**Issue by mattias800** [mbrookes/formsy-material-ui#60]
material-ui has released an alpha of 0.15 where onEnterKeyDown has been deprecated.
This causes a warning in the console:
```
Warning: "onEnterKeyDown" property of "TextField" has been deprecated.
Use onKeyDown and check for keycode instead.
```

**Comment by mbrookes** [comment]
Thanks, yes, this doesn't support 0.15.0 yet. It hasn't been released. :smile: 

We'll add support between now and when it is, but feel free to submit a PR in the meantime.

**Comment by reohjs** [comment]
If you want to supress the error till this gets updated, you can change the key on line 57 to 'onKeyDown' in `node_modules/formsy-material-ui/lib/FormsyText.js`

**Comment by izziaraffaele** [comment]
According to material-ui doc ( http://www.material-ui.com/#/components/text-field ) a controlled TextField component must be managed with the onChange prop.

That is probably what is causing this as well https://github.com/mbrookes/formsy-material-ui/issues/68
