### ISSUE TITLE
FormsyTime - value not updated after time picked

### ISSUE THREAD

**Issue by LiShine** [mbrookes/formsy-material-ui#62]
Using the example from formsy-material-ui github page.
The other fields work but FormsyTime - value is not shown when time picked.
When using TimePicker itself, it works

**Comment by mbrookes** [comment]
Did you actually pick a time, or just click OK? If the latter, it's a MUI bug. 

The same code for FormsyTime is here: https://github.com/mbrookes/formsy-mui-demo/blob/master/Form.jsx

Hand can be seen working at the site linked from the README in that Repo.

**Comment by LiShine** [comment]
I actually pick the time and then click ok
I am using the new Meteor beta
Same class as in Form.jsx

import React from 'react'
import * as rb from 'react-bootstrap'
import injectTapEventPlugin from 'react-tap-event-plugin';
import { FormsyCheckbox, FormsyDate, FormsyRadio, FormsyRadioGroup, FormsySelect, FormsyText, FormsyTime, FormsyToggle } from 'formsy-material-ui'
import RaisedButton from 'material-ui/lib/raised-button'
import MenuItem from 'material-ui/lib/menus/menu-item'
import TimePicker from 'material-ui/lib/time-picker'
import Paper from 'material-ui/lib/paper'
import Styles from 'material-ui/lib/styles'
injectTapEventPlugin();

export default React.createClass({

	childContextTypes: {
		muiTheme: React.PropTypes.object
	},

	getChildContext(){
		return {
			muiTheme: Styles.ThemeManager.getMuiTheme(Styles.LightRawTheme)
		}
	},

	getInitialState() {
		return {
			canSumbit: false
		};
	},

	errorMessages: {
		wordsError: "Please only use letters",
		numericError: "Please provide a number",
		urlError: "Please provide a valid URL"
	},

	styles: {
		paperStyle: {
			width: 300,
			margin: 'auto',
			padding: 20
		},
		switchStyle: {
			marginBottom:16
		},
		submitStyle: {
			marginTop: 32
		}
	},

	enableButton() {
		this.setState({
			canSubmit: true
		});
	},

	disableButton() {
		this.setState({
			canSubmit: false
		});
	},

	submitForm(data) {
		alert(JSON.stringify(data, null, 4));
	},

	notifyFormError(data) {
		console.error('Form error:', data);
	},

	render() {
		let {paperStyle, switchStyle, submitStyle } = this.styles;
		let { wordsError, numericError, urlError } = this.errorMessages;

		return (
			<Paper style={paperStyle}>

				<Formsy.Form
					onValid={this.enableButton}
					onInvalid={this.disableButton}
					onValidSubmit={this.submitForm}
					onInvalidSubmit={this.notifyFormError}
				>

					<FormsyText
						name="name"
						validations="isWords"
						validationError={wordsError}
						required
						hintText="What is your name?"
						floatingLabelText="Name"
					/>

					<FormsyText
						name="age"
						validations="isNumeric"
						validationError={numericError}
						hintText="Are you a wrinkly?"
						floatingLabelText="Age (optional)"
					/>

					<FormsyText
						name="url"
						validations="isUrl"
						validationError={urlError}
						required
						defaultValue="http://"
						hintText="http://www.example.com"
						floatingLabelText="URL"
					/>

					<FormsySelect
						name="frequency"
						required
						floatingLabelText="How often do you?"
						menuItems={this.selectFieldItems}
					>
						<MenuItem value={'never'} primaryText="Never" />
						<MenuItem value={'nightly'} primaryText="Every Night" />
						<MenuItem value={'weeknights'} primaryText="Weeknights" />
					</FormsySelect>

					<FormsyDate
						name="date"
						required
						floatingLabelText="Date"
					/>

					<FormsyTime
						name="time"
						required
						floatingLabelText="Time"
					/>

					<FormsyCheckbox
						name="agree"
						label="Do you agree to disagree?"
						style={switchStyle}
					/>

					<FormsyToggle
						name="toggle"
						label="Toggle"
						style={switchStyle}
					/>

					<FormsyRadioGroup name="shipSpeed" defaultSelected="not_light">
						<FormsyRadio
							value="light"
							label="prepare for light speed"
							style={switchStyle}
						/>
						<FormsyRadio
							value="not_light"
							label="light speed too slow"
							style={switchStyle}
						/>
						<FormsyRadio
							value="ludicrous"
							label="go to ludicrous speed"
							style={switchStyle}
							disabled={true}
						/>
					</FormsyRadioGroup>

					<RaisedButton
						style={submitStyle}
						type="submit"
						label="Submit"
						disabled={!this.state.canSubmit}
					/>
				</Formsy.Form>
			</Paper>
		);
	}
});

**Comment by mbrookes** [comment]
Hi @LiShine - I can't reproduce this with the current version. Is this still an issue?

**Comment by mbrookes** [comment]
Closing due to no response.
