### ISSUE TITLE
Text PropType

### ISSUE THREAD

**Issue by scrambled2k3** [mbrookes/formsy-material-ui#65]
It would be nice for the value of a FormsyText component to accept numbers as well instead of just strings.  The material-ui TextField accepts of Proptype of "any".  If you think this is a valid change, I can submit a PR.

**Comment by mbrookes** [comment]
Makes sense, go ahead.

**Comment by scrambled2k3** [comment]
PR submitted: #66

**Comment by mbrookes** [comment]
Included on 0.3.9  & 0.4.0 releases. Thanks, and sorry for the delay in merging.
