### ISSUE TITLE
FormsyText is really slow

### ISSUE THREAD

**Issue by stueynet** [mbrookes/formsy-material-ui#68]
I find the text inputs and checkboxes to be really slow when you type. Its fine if you type 1 letter but if you try to type a few words it lags like crazy. This occurs in your demo page as well. Any thoughts?

**Comment by brandonmp** [comment]
concur-anyone know a way to mitigate this? if i swap out the components for regular MUI textfields, the lag disappears, but it's not clear how to wire that into the Formsy.Form.

**Comment by reohjs** [comment]
@brandonmp https://github.com/mbrookes/formsy-material-ui/issues/54#issuecomment-192470948

**Comment by bschnelle** [comment]
It's pretty slow in the demo in the docs as well.

**Comment by mbrookes** [comment]
Closed with temp switch to uncontrolled use. We will have to revisit this in the future when Material-UI become controlled only.

**Comment by protoEvangelion** [comment]
Is there any update on this?  My forms are still pretty slow when typing in a text field...

**Comment by rojobuffalo** [comment]
Are you using the latest version? It's not noticeably slowed down for my app.

**Comment by protoEvangelion** [comment]
Yes I am using v0.5.5.  Thanks for the quick response :) I think it was an issue with my CPU because it is working fine now!

**Comment by rojobuffalo** [comment]
Ok, good to know.
