### ISSUE TITLE
Having validationError set without 'required' shows error text all the time

### ISSUE THREAD

**Issue by sys13** [mbrookes/formsy-material-ui#7]
![2015-10-22 11 45 38](https://cloud.githubusercontent.com/assets/1377089/10656567/a4bd7822-78b2-11e5-926f-6084e7faf3f6.png)

Might want to only set `errorText` on the TextField if `this.showError` is true.

**Comment by sys13** [comment]
It also disables the submit button.

**Comment by mbrookes** [comment]
Odd, I didn't think formsy was supposed to return an error on a "pristine" form element (one that hasn't been edited).

**Comment by mbrookes** [comment]
Looks like #19 / 0.2.4 fixed this. Daniel, can you confirm?

**Comment by sys13** [comment]
Works!
