### ISSUE TITLE
FormsyDate causes  Uncaught Invariant Violation

### ISSUE THREAD

**Issue by Miteshdv** [mbrookes/formsy-material-ui#76]
Hi I am trying to use FormsyDate DateField type input for form to format date.
But i am getting following error

Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

Please let me know what mite be wrong

**Comment by Miteshdv** [comment]
Any update on this please!

**Comment by mbrookes** [comment]
Here's what might be wrong:

```
You might be adding a ref to a component that was not created inside a component's render method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

**Comment by Miteshdv** [comment]
Is there some way to fix this i dont know what wrong i am doing , request you to help me out please

**Comment by mbrookes** [comment]
Make sure you don't have multiple copes of react in `node_models` and its subfolders, particularly `material-ui`.

**Comment by Miteshdv** [comment]
I wish i knew how to figure this out , well there are lots of libraries in my project.I will try to find .Thanks

**Comment by mbrookes** [comment]
Just delete 'node_modules' and 'mom install'

**Comment by mbrookes** [comment]
'npm install'

**Comment by Miteshdv** [comment]
Ok that worked thanks ! But i dnt know why the FormsyDate Component is showing nothing .. no date field no text input not errors ! any idea on this please
