### ISSUE TITLE
this.handleEnterKeyDown is not a function for FormsyText

### ISSUE THREAD

**Issue by quangdng** [mbrookes/formsy-material-ui#83]
Hi guys,

React pops up an error in FormsyText when we are trying to press Enter key instead of clicking on Submit button. It does not severely affect the form though.

In addition, when looking at FormsyText.jsx, there is no reference to this.handleEnterKeyDown. This is possibly a bug.

**Comment by maticrivo** [comment]
@quangdng, actually FormsyText.jsx does reference `this.handleEnterKeyDown`
https://github.com/mbrookes/formsy-material-ui/blob/master/src/FormsyText.jsx#L23

and it is not defined anywhere..

**Comment by quangdng** [comment]
https://github.com/mbrookes/formsy-material-ui/pull/84

I created a pull request to fix this issue. Hopefully this is the right fix.

**Comment by keremciu** [comment]
@quangdng @mbrookes #84 and #87 is really important fixes, I think we need urgent new version for them I can't use this library because of these problems :(

**Comment by mbrookes** [comment]
Folks, I'm travelling this week, so will only be able to review next week. In the interim, you can point your package.json to a fixed fork.

**Comment by mbrookes** [comment]
Fixed in master. Could someone test it out?

**Comment by quangdng** [comment]
Tested. The bug was fixed. Thanks all.
