### ISSUE TITLE
File Upload Field

### ISSUE THREAD

**Issue by onimisionipe** [mbrookes/formsy-material-ui#89]
I'm curious as to why there's no file upload field. any alternative?

**Comment by mbrookes** [comment]
http://www.material-ui.com/v0.15.0-beta.2/#/components/raised-button

See Complex example, - choose an image.

**Comment by acomito** [comment]
You'll need to write some code with state or refs to get this to work-- which isn't the end of the world but it would be nice to have a stand alone component mixed into formsy-material-ui's submit method. Formsy components has a nice <File /> component.
