### ISSUE TITLE
"Uncaught TypeError: this.handleEnterKeyDown is not a function" exception at FormsyText.js:47.

### ISSUE THREAD

**Issue by vrecluse** [mbrookes/formsy-material-ui#90]
After updated to latest version then press enter when typing in FormsyText.

**Comment by claytonmarinho** [comment]
Have you tried onKeyDown?

"Deprecated. Use onKeyDown and check for keycode instead.

The function to call when the user presses the Enter key."

**Comment by mbrookes** [comment]
Closing for now as this is a MUI API change.

**Comment by vrecluse** [comment]
It seems not a MUI API issue...Is this code ok? It calls this.handleEnterKeyDown without existence checking.
At FormsyText.jsx:22:
```
  handleKeyDown: function handleKeyDown(event) {
    if (keycode(event) === 'enter') this.handleEnterKeyDown(event);
    if (this.props.onKeyDown) this.props.onKeyDown(event, event.currentTarget.value);
  },
```

**Comment by mbrookes** [comment]
What version are you using?

**Comment by vrecluse** [comment]
0.4.0 via npm.

**Comment by mbrookes** [comment]
Try the current version.
