### ISSUE TITLE
FormsyCheckbox trigger allot of React warnings

### ISSUE THREAD

**Issue by tanneess** [mbrookes/formsy-material-ui#91]
Hi, the following happens when FormsyCheckbox is being added to the form with defaultChecked

warning.js:44 Warning: Input elements must be either controlled or uncontrolled (specify either the checked prop, or the defaultChecked prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props

warning.js:44 Warning: EnhancedSwitch is changing a uncontrolled input of type checkbox to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component

warning.js:44 Warning: EnhancedSwitch is changing a controlled input of type checkbox to be uncontrolled. Input elements should not switch from controlled to uncontrolled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component

The first warning tells the all story. By experimenting a bit, I found out that this is fixed by changing the render method of FormsyCheckbox to this.

    render: function render() {
    var value = this.getValue();
    var defaultChecked = this.props.defaultChecked;
      var newProps={};
      for(var p in this.props){
          newProps[p]=this.props[p];
      }
      delete newProps.defaultChecked;

    if (typeof value === 'undefined') value = typeof defaultChecked !== 'undefined' ? defaultChecked : false;

    return _react2.default.createElement(_Checkbox2.default, _extends({}, newProps, {
      ref: this._setMuiComponentAndMaybeFocus,
      onCheck: this.handleValueChange,
      checked: value
    }));
      }

This seems to provide the solution. Basically it remove the no longer needed defaultChecked from the props before sending it to the Checkbox component.

**Comment by tanneess** [comment]
Actually this also happens for TextField. Am I doing something wrong here or is this a general issue?

**Comment by mbrookes** [comment]
@tanneess - it seems to be a general issue after upgrading to latest versions of React, MUI and Formsy. I'll look into it when I get a chance.

**Comment by ochervak** [comment]
Looks like fix should be the same as for inputs...

**Comment by mbrookes** [comment]
@ochervak - yes, I'm going to update all the components to this approach when I get a moment.

**Comment by ochervak** [comment]
@mbrookes many thanks!

**Comment by mbrookes** [comment]
Okay guys, try master.

**Comment by ochervak** [comment]
@mbrookes i'm really appreciate your hard work!

**Comment by mbrookes** [comment]
@ochervak NP - is it working for you now with master?

**Comment by ochervak** [comment]
@mbrookes i tried to install it from master with 
```"formsy-material-ui": "git://github.com/mbrookes/formsy-material-ui#13d28637b2d3453d51fc95206c1deab31a43e99a",```
But my import fail... For example that:
`import FormsySelect from 'formsy-material-ui/FormsySelect';`

What i'm doing wrong ?

**Comment by mbrookes** [comment]
Hi @ochervak the problem is that github doesn't have the babel transpiled lib directory, so you'll need to:
```
cd node_modules/formsy-material-ui && npm run build
```

**Comment by ochervak** [comment]
@mbrookes thanks. now i impored all things, but now 
```invariant.js:38 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).```

Warning appears...

**Comment by mbrookes** [comment]
"you have multiple copies of React loaded"

Check if you have `react` in `node_modules/formsy-material-ui/node_modules` or `node_modules/material-ui/node_modules` and `rm -rf` it if so.

**Comment by ochervak** [comment]
@mbrookes yes, your right. i deleted node_modules, and all works fine!
checkboxes and select fields are confirmed! thanks

**Comment by mbrookes** [comment]
0.4.2 released.
