### ISSUE TITLE
[FormsyText] causes error : Cannot read property 'prepareStyles' of undefined

### ISSUE THREAD

**Issue by 0xori** [mbrookes/formsy-material-ui#92]
on this line:  var prepareStyles = this.context.muiTheme.prepareStyles;
after this warning: Failed Context Types: Required context `muiTheme` was not specified in `TextField`. Check the render method of `FormsyText`.

**Comment by mbrookes** [comment]
You need to add `muiTheme` on context using `MuiThemeProvider`: http://www.material-ui.com/v0.15.0-beta.2/#/get-started/usage

Or manually:

http://www.material-ui.com/v0.15.0-beta.2/#/customization/themes

(See 'Using context')
