### ISSUE TITLE
[FormsyText] not showing default value

### ISSUE THREAD

**Issue by 0xori** [mbrookes/formsy-material-ui#93]
Hi, I'm trying to show a default value on FormsyText.

I have tried with `value `prop & with `defaultValue `prop
this is example of my render method:

`render: function () {
    var firstName = "John";

     return(
       <Formsy.Form id="form-register-pa-1" ref="myForm"
                             onValidSubmit={this._handleValidSubmit}
                             onValid={this.enableSubmitButton}
                             onInvalid={this.disableSubmitButton}>
   
          <FormsyText
                   name="inputFirst"
                   id="inputFirst"
                   defaultValue={firstName}
                   floatingLabelText="First Name"
                   required
                   />
       </Formsy.Form>
    )
}`

**Comment by mbrookes** [comment]
Can you try with master?

**Comment by 0xori** [comment]
I tried both with master.. still not working

**Comment by mbrookes** [comment]
@0xori - could you copy & paste the `propTypes` block from `node_modules/formsy-material-ui/lib/FormsyText`?

**Comment by 0xori** [comment]
`  propTypes: {
    name: _react2.default.PropTypes.string.isRequired,
    value: _react2.default.PropTypes.any,
    onFocus: _react2.default.PropTypes.func,
    onBlur: _react2.default.PropTypes.func
  },`

**Comment by mbrookes** [comment]
@0xori - thanks, that isn't master in that case.

**Comment by mbrookes** [comment]
0.4.2 released. Please reopen if that doesn't fix your issue after updating.
