### ISSUE TITLE
Update peerDependency for Material-ui

### ISSUE THREAD

**Issue by krijoh92** [mbrookes/formsy-material-ui#98]
I see you have material-ui@0.15.0-beta.1 as a peer dependency in package.json

Materail-UI has now released 0.15.0, and it's no longer in beta. 
https://github.com/callemall/material-ui/blob/master/CHANGELOG.md#0150

**Comment by mbrookes** [comment]
Yup, although whatever you specify in your project will overrule. 

But updated now, and thanks for the reminder.

**Comment by krijoh92** [comment]
Thanks! Yeah I know, just that pesky little warning from npm install ;)
