### ISSUE TITLE
Autofill input not detected

### ISSUE THREAD

**Issue by kand617** [mbrookes/formsy-material-ui#99]
Hi, 

I have two text fields that are being auto filled by chrome. Formsy does not detect values from the browser, so I have to click in both text fields to enable the button. 

Is there a way around this?

![image](https://cloud.githubusercontent.com/assets/5092518/15146544/2c155afa-1710-11e6-993a-525e0d66d938.png)

**Comment by mbrookes** [comment]
@kand617 That's a MUI issue: https://github.com/callemall/material-ui/issues/718

**Comment by devdlabs** [comment]
Maybe better to keep this issue as open till mui fixed it ?
